server:
  port: 8882
  address: 0.0.0.0
  servlet:
    context-path: /inventory-service

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_inventory?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      initial-size: 20
      min-idle: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9412

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 60000ms

redisson:
  address: redis://${spring.redis.host}:${spring.redis.port}
  password: ${spring.redis.password}

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 5
      scheduledDelay: 128
      scheduledThreadMax: 10
      started: false
      repositorySupport: redis
      hmilyRedisConfig:
        hostName: ${spring.redis.host}
        port: ${spring.redis.port}
        password: ${spring.redis.password}

mybatis:
  type-aliases-package: com.hengxunda.springcloud.inventory.entity
  config-location: classpath:mybatis/mybatis-config.xml

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}