server:
  port: 9884
  address: 0.0.0.0
  servlet:
    context-path: /nio-service

spring:
  application:
    name: nio-service
  zipkin:
    base-url: http://127.0.0.1:9413

#eureka:
#  client:
#    service-url:
#      default-zone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8861/eureka/,http://127.0.0.1:8961/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}