server:
  port: 9413
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: zipkin-service

#eureka:
#  client:
#    service-url:
#      default-zone: http://192.168.0.88:8761/eureka/,http://192.168.0.88:8861/eureka/,http://192.168.0.88:8961/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  metrics:
    web:
      server:
        auto-time-requests: false


